[package]
name = "polars-stream"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Private crate for the streaming execution engine for the Polars DataFrame library"

[dependencies]
atomic-waker = { workspace = true }
crossbeam-deque = { workspace = true }
crossbeam-utils = { workspace = true }
futures = { workspace = true }
memmap = { workspace = true }
parking_lot = { workspace = true }
pin-project-lite = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
recursive = { workspace = true }
slotmap = { workspace = true }
tokio = { workspace = true }

polars-core = { workspace = true }
polars-error = { workspace = true }
polars-expr = { workspace = true }
polars-io = { workspace = true, features = ["cloud"] }
polars-mem-engine = { workspace = true }
polars-parquet = { workspace = true }
polars-plan = { workspace = true }
polars-utils = { workspace = true }

[build-dependencies]
version_check = { workspace = true }

[features]
nightly = []
bitwise = ["polars-core/bitwise", "polars-plan/bitwise"]
merge_sorted = ["polars-plan/merge_sorted"]
dynamic_group_by = []
strings = []

parquet = ["polars-mem-engine/parquet", "polars-plan/parquet"]
ipc = ["polars-mem-engine/ipc", "polars-plan/ipc"]
csv = ["polars-mem-engine/csv", "polars-plan/csv"]
json = ["polars-mem-engine/json", "polars-plan/json"]

cloud = ["polars-mem-engine/cloud", "polars-plan/cloud"]

python = ["polars-mem-engine/python", "polars-plan/python"]

# We need to specify default features here to match workspace defaults.
# Otherwise we get warnings with cargo check/clippy.
default = [
  "parquet",
  "ipc",
  "csv",
  "json",
  "cloud",
  "bitwise",
  "python",
]
